此文件处理的交互数据，完成与KG中id的对齐

In [20]:
import pandas as pd
java = pd.read_csv('./processed/java_nodul.csv', header=0, sep='\t')
java_count = java.groupby('stuno').count()
java = java[java['stuno'].isin(java_count[java_count['oper']>3].index)][['stuno','title','new_oper','time']]
java

                 stuno            title  new_oper        time
0     1069800109030205          Java运算符     watch  1406863244
1     1069800109030205  StringTokenizer      done  1410874261
2     1069800109030205      Java Applet      done  1410874265
3     1069800109030205      Java Applet  duration  1410874275
4     1069800109030205         Java成员方法      done  1410913417
...                ...              ...       ...         ...
2885  1069850614030038         Java语言背景      done  1429083169
2886  1069850614030038         Java语言背景       tag  1429083255
2887  1069850614030038         Java语言背景  duration  1429083393
2888  1069850614030038           网络通信基础      done  1429084813
2889  1069850614030038           网络通信基础  duration  1429085601

[2494 rows x 4 columns]

In [21]:
java_dict = pd.read_csv('./java/entity2id.txt',sep='\t', names=['entity','id'])
java_dict

                    entity   id
0                   Java语言    1
1                 Java语言背景    2
2                    Oak软件    3
3                   Java应用    4
4                     网络应用    5
..                     ...  ...
358              Java基本网络类  359
359                  URL通信  360
360                  TCP通信  361
361  UDP通信********第十章 网络通信  362
362                   课程复习  363

[363 rows x 2 columns]

In [22]:
java_dict = java_dict.set_index('entity')['id'].to_dict()
java['new_title'] = java['title'].apply(lambda x: True if java_dict.get(x) else False)

In [23]:
java[java['new_title']==False]

                 stuno        title  new_oper        time  new_title
2     1069800109030205  Java Applet      done  1410874265      False
3     1069800109030205  Java Applet  duration  1410874275      False
4     1069800109030205     Java成员方法      done  1410913417      False
5     1069800109030205   JAVA语言(简版)       tag  1410925379      False
6     1069800109030205       JAVA语言       tag  1410925409      False
...                ...          ...       ...         ...        ...
2879  1069834614030046           论坛     watch  1411123740      False
2881  1069850614030038         离线作业     enter  1415934808      False
2882  1069850614030038         离线作业      done  1415934818      False
2883  1069850614030038         课程公告     watch  1418687894      False
2884  1069850614030038    JAVA语言(新)       tag  1429083139      False

[1083 rows x 5 columns]

In [24]:
set(java[java['new_title']==False]['title'].unique())

{'5',
 '?',
 'JAVA语言',
 'JAVA语言(新)',
 'JAVA语言(简版)',
 'Java',
 'Java Applet',
 'Java?',
 'Java??',
 'JavaJDK',
 'Java开发环境与JDK',
 'Java成员变量',
 'Java成员方法',
 'Java类定义',
 'Java跳转语句',
 'TCP',
 'java语言(新)',
 '声明与抛掷异常',
 '子类继承特性',
 '对象操作',
 '布局管理器',
 '构造方法与抽象类',
 '生产者--消费者问题',
 '离线作业',
 '第01讲',
 '第02讲',
 '第03讲',
 '第19讲',
 '第51讲',
 '第54讲',
 '第59讲',
 '类的基本特征',
 '计算机的发展',
 '论坛',
 '课程公告',
 '面向对象基础'}

In [25]:
def change(x):
    if x in ['5','?','JAVA语言','JAVA语言（新）','JAVA语言(新)','JAVA语言（简版）','JAVA语言(简版)','java语言(新)','Java','Java?','Java??']:
        return 'Java语言'
    elif x in ['Java Applet']:
        return 'Java Applet/Java小应用程序'
    elif x in ['JavaJDK', 'Java开发环境与JDK']:
        return 'Java开发环境与JDK（包含40）'
    elif x in ['Java成员变量']:
        return 'Java成员变量（包含131,132,84）'
    elif x in ['Java成员方法']:
        return 'Java成员方法（包含131,132,138,139）'
    elif x in ['Java类定义']:
        return 'Java类定义（包含16）'
    elif x in  ['Java跳转语句']:
        return '跳转语句'
    elif x in ['TCP']:
        return 'TCP通信'
    elif x in ['声明与抛掷异常']:
        return '声明与抛掷异常（包含206,207）'
    elif x in ['子类继承特性']:
        return '子类继承特性（包含20,153）'
    elif x in ['对象操作']:
        return '对象操作（包含17）'
    elif x in ['布局管理器']:
        return '布局管理器类'
    elif x in ['构造方法与抽象类']:
        return '构造方法与抽象类（包含133）'
    elif x in ['生产者--消费者问题']:
        return '生产者-消费者问题********第九章 多线程'
    elif x in ['类的基本特征']:
        return '类的基本特征（包含16,19,20,21）'
    elif x in ['面向对象基础']:
        return '面向对象基础（包含15,16,17,19,20,21）'
    elif x in ['离线作业']:
        return '课程复习'
    elif x in ['第01讲', '第02讲', '第03讲', '第19讲', '第51讲', '第54讲', '第59讲','计算机的发展', '论坛', '课程公告']:
        return 'Java语言'
    else:
        return x

In [26]:
java['title'] = java['title'].apply(lambda x: change(x))
java['new_title'] = java['title'].apply(lambda x: True if java_dict.get(x) else False)
java[java['new_title']==False]

Empty DataFrame
Columns: [stuno, title, new_oper, time, new_title]
Index: []

In [27]:
java

,stuno,title,new_oper,time,new_title
0,1069800109030205,Java运算符,watch,1406863244,True
1,1069800109030205,StringTokenizer,done,1410874261,True
2,1069800109030205,Java Applet/Java小应用程序,done,1410874265,True
3,1069800109030205,Java Applet/Java小应用程序,duration,1410874275,True
4,1069800109030205,"Java成员方法（包含131,132,138,139）",done,1410913417,True
...,...,...,...,...,...
2885,1069850614030038,Java语言背景,done,1429083169,True
2886,1069850614030038,Java语言背景,tag,1429083255,True
2887,1069850614030038,Java语言背景,duration,1429083393,True
2888,1069850614030038,网络通信基础,done,1429084813,True
2889,1069850614030038,网络通信基础,duration,1429085601,True

In [28]:
java['new_title2'] = java['title'].apply(lambda x: java_dict.get(x))
java

,stuno,title,new_oper,time,new_title,new_title2
0,1069800109030205,Java运算符,watch,1406863244,True,305
1,1069800109030205,StringTokenizer,done,1410874261,True,172
2,1069800109030205,Java Applet/Java小应用程序,done,1410874265,True,54
3,1069800109030205,Java Applet/Java小应用程序,duration,1410874275,True,54
4,1069800109030205,"Java成员方法（包含131,132,138,139）",done,1410913417,True,314
...,...,...,...,...,...,...
2885,1069850614030038,Java语言背景,done,1429083169,True,294
2886,1069850614030038,Java语言背景,tag,1429083255,True,294
2887,1069850614030038,Java语言背景,duration,1429083393,True,294
2888,1069850614030038,网络通信基础,done,1429084813,True,357
2889,1069850614030038,网络通信基础,duration,1429085601,True,357

In [29]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

java.sort_values(by=['stuno','time'])
java[['new_stuno']] = java[['stuno']].apply(encoder.fit_transform)
new_java = java[['new_stuno','new_title2','new_oper','time']]
new_java['new_stuno'] = new_java['new_stuno'] + 1

/opt/conda/envs/KT_RL/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [30]:
new_java

      new_stuno  new_title2  new_oper        time
0             1         305     watch  1406863244
1             1         172      done  1410874261
2             1          54      done  1410874265
3             1          54  duration  1410874275
4             1         314      done  1410913417
...         ...         ...       ...         ...
2885        183         294      done  1429083169
2886        183         294       tag  1429083255
2887        183         294  duration  1429083393
2888        183         357      done  1429084813
2889        183         357  duration  1429085601

[2494 rows x 4 columns]

In [31]:
new_java.to_csv('./processed/java_mb_KG.txt',header=None, sep='\t', index=False)

In [33]:
max(new_java['new_title2'])

363

In [18]:
import pandas as pd
os = pd.read_csv('./processed/os_nodul.csv', header=0, sep='\t')
os_count = os.groupby('stuno').count()
os = os[os['stuno'].isin(os_count[os_count['oper']>3].index)][['stuno','title','new_oper','time']]
os

                 stuno         title  new_oper        time
0     1069800109030205     操作系统原理(新)       tag  1429497734
1     1069800109030205        连续分配方式      done  1429497741
2     1069800109030205            对换      done  1429497796
3     1069800109030205  三级调度的概念及算法准则      done  1429497920
4     1069800109030205        连续分配方式       tag  1429499516
...                ...           ...       ...         ...
5601  1069834615030039     系统安全的基本概念  duration  1428396833
5602  1069850614030008     操作系统原理(新)       tag  1428674222
5603  1069850614030008    单道和多道批处理系统      done  1428674265
5604  1069850614030008    单道和多道批处理系统  duration  1428677285
5605  1069850614030008    单道和多道批处理系统       tag  1428677286

[4700 rows x 4 columns]

In [19]:
os_dict = pd.read_csv('./os/entity2id.txt',sep='\t', names=['entity','id'])
os_dict

                        entity   id
0                        计算机系统    1
1                        计算机硬件    2
2                        计算机软件    3
3                         系统软件    4
4                         应用软件    5
..                         ...  ...
491                    设备管理（2）  492
492                    文件管理（1）  493
493  文件管理（2）====第十章 UNIX系统内核结构  494
494                    复习串讲（1）  495
495                    复习串讲（2）  496

[496 rows x 2 columns]

In [20]:
os_dict = os_dict.set_index('entity')['id'].to_dict()
os['new_title'] = os['title'].apply(lambda x: True if os_dict.get(x) else False)

In [21]:
os[os['new_title']==False]

                 stuno      title new_oper        time  new_title
0     1069800109030205  操作系统原理(新)      tag  1429497734      False
16    1069800113030074       离线作业    enter  1416551185      False
17    1069800113030074       离线作业     done  1416551190      False
18    1069800113030074  操作系统原理(新)      tag  1427191489      False
19    1069800113030074       课程公告    watch  1427191494      False
...                ...        ...      ...         ...        ...
5594  1069834614030133       课程公告    watch  1429361907      False
5595  1069834614030133       离线作业    enter  1429363362      False
5596  1069834614030133       离线作业     done  1429363372      False
5597  1069834614030133  操作系统原理(新)      tag  1429980236      False
5602  1069850614030008  操作系统原理(新)      tag  1428674222      False

[2482 rows x 5 columns]

In [6]:
os['title'].nunique()

188

In [7]:
len(set(os[os['new_title']==False]['title'].unique()))

98

In [8]:
set(os[os['new_title']==True]['title'].unique())

{'I/O设备的控制方式',
 'I/O设备的类型和控制器',
 'I/O通道和总线系统',
 'Internet的发展与服务',
 'SPOOLING技术',
 'TCP/IP网络体系结构',
 'UNIX系统概述',
 'UNIX系统调用',
 'shell语言的简单命令',
 '三级调度的概念及算法准则',
 '产生死锁的原因和必要条件',
 '信号量机制及应用',
 '分时系统和实时系统',
 '利用银行家算法避免死锁(1)',
 '利用银行家算法避免死锁(2)',
 '单道和多道批处理系统',
 '命令解释程序的作用',
 '基于口令与物理标志的认证技术',
 '基于生物标志和公开密钥的认证技术',
 '基本分段存储管理方式',
 '基本分页存储管理方式(1)',
 '基本分页存储管理方式(2)',
 '处理机和存储器管理功能',
 '复习串讲（1）',
 '复习串讲（2）',
 '外存分配方式',
 '多处理器系统中的调度',
 '存储器管理',
 '实时调度',
 '客户/服务器模式',
 '对换',
 '开放系统互连参考模型',
 '操作系统的基本特性',
 '操作系统的目标和作用',
 '操作系统的结构设计(1)',
 '数字签名与网络加密技术',
 '数据加密与加密算法',
 '文件共享和文件保护',
 '文件和文件类型',
 '文件存储空间的管理',
 '文件的逻辑结构',
 '文件管理（1）',
 '目录管理',
 '磁盘存储器性能简述',
 '磁盘调度和高速缓存',
 '程序的装入链接',
 '程序的顺序和并发执行及其特征',
 '管程机制',
 '系统安全的基本概念',
 '系统调用(1)',
 '系统调用(2)',
 '线程(1)',
 '经典进程的同步问题',
 '缓冲管理(1)',
 '缓冲管理(2)',
 '网络操作系统提供的服务',
 '网络操作系统的功能(1)',
 '网络操作系统的功能(2)',
 '联机命令接口',
 '虚拟存储器的概念和实现方法',
 '计算机局域网络',
 '计算机广域网络',
 '计算机病毒的概念与类型',
 '计算机网络的拓扑结构',
 '设备分配和设备独立性(1)',
 '设备分配和设备独立性(2)',
 '设备管理和文件管理功能',
 '设备管理（1）',
 '设备管理（2）',
 '访问控制矩阵的实现',
 '访问矩阵及修改',
 '请求分页存储管理方式(1)',
 '请求分页存储管理方式(2)',
 '调度算法(1)',
 '调度算法(2)',
 '进程同步的概念',
 '进程控制(1)',
 '进程控制(2)',
 '进程控制与调度',
 '进程的同步与通信（1）',
 '进程的同步与通信（2）',
 '进程的描述',
 '进程的特征与状态',
 '进程通信的类型(1)',
 '进程通信的类型(2)',
 '连续分配方式',
 '重定向与管道命令',
 '键盘终端处理程序',
 '页面置换算法',
 '预防死锁的方法'}

In [5]:
set(os[os['new_title']==False]['title'].unique())

{'8086/8088CPU的创新',
 '?3??',
 '??',
 '???',
 '????',
 '???м',
 '??ο?',
 'Java数据类型及转换',
 'androidphone-单道和多道批处理系统',
 'androidphone-命令解释程序的作用',
 'androidphone-复习串讲（1）',
 'androidphone-计算机网络的拓扑结构',
 'androidphone-键盘终端处理程序',
 '图形用户接口',
 '提高磁盘I/O速度的其他方法',
 '操作系统原理(教育网)',
 '操作系统原理(新)',
 '操作系统原理(电信网)',
 '操作系统原理(简版)',
 '操作系统的结构设计(2)',
 '数据的一致性控制',
 '文件管理（2）',
 '死锁的检测和解除',
 '流的概念',
 '病毒的隐藏、预防及检测',
 '离线作业',
 '第01讲',
 '第02讲',
 '第03讲',
 '第04讲',
 '第05讲',
 '第06讲',
 '第07讲',
 '第08讲',
 '第09讲',
 '第10讲',
 '第11讲',
 '第12讲',
 '第13讲',
 '第14讲',
 '第15讲',
 '第16讲',
 '第17讲',
 '第18讲',
 '第19讲',
 '第20讲',
 '第21讲',
 '第22讲',
 '第23讲',
 '第24讲',
 '第25讲',
 '第26讲',
 '第27讲',
 '第28讲',
 '第29讲',
 '第30讲',
 '第31讲',
 '第32讲',
 '第33讲',
 '第34讲',
 '第35讲',
 '第36讲',
 '第37讲',
 '第38讲',
 '第39讲',
 '第40讲',
 '第41讲',
 '第42讲',
 '第43讲',
 '第44讲',
 '第45讲',
 '第46讲',
 '第47讲',
 '第48讲',
 '第49讲',
 '第50讲',
 '第51讲',
 '第52讲',
 '第53讲',
 '第54讲',
 '第55讲',
 '第56讲',
 '第57讲',
 '第58讲',
 '第59讲',
 '第60讲',
 '第61讲',
 '第62讲',
 '第63讲',
 '第64讲',
 '第70讲',
 '第75讲',
 '线程(2)',
 '论坛',
 '设备处理',
 '请求分段存储管理方式',
 '课程介绍',
 '课程公告'}

In [26]:
def change_os(x):
    if x in ['8086/8088CPU的创新', '?3??', '??', '???', '????', '???м', '??ο?','课程介绍', '课程公告', '操作系统原理(教育网)', '操作系统原理(新)', '操作系统原理(电信网)', '操作系统原理(简版)','论坛','离线作业']:
        return '操作系统的目标和作用'
    elif x in ['Java数据类型及转换']:
        return '数据一致性'
    elif x in ['androidphone-单道和多道批处理系统']:
        return '单道和多道批处理系统'
    elif x in ['androidphone-命令解释程序的作用']:
        return '命令解释程序的作用'
    elif x in [ 'androidphone-复习串讲（1）']:
        return '复习串讲（1）'
    elif x in ['androidphone-计算机网络的拓扑结构']:
        return '计算机网络的拓扑结构'
    elif x in ['androidphone-键盘终端处理程序']:
        return '键盘终端处理程序'
    elif x in ['图形用户接口']:
        return '图形用户接口====第七章 操作系统的接口'
    elif x in ['操作系统的结构设计(2)']:
        return '操作系统的结构设计(2)====第一章 操作系统引论'
    elif x in ['提高磁盘I/O速度的其他方法']:
        return '提高磁盘I/O速度的其他方法====第五章 设备管理'
    elif x in ['线程(2)']:
        return '线程(2)====第二章 进程管理'
    elif x in ['网络操作系统提供的服务']:
        return '网络操作系统提供的服务====第八章 网络操作系统'
    elif x in ['数据的一致性控制']:
        return '数据的一致性控制====第六章 文件和文件系统'
    elif x in ['文件管理（2）']:
        return '文件管理（2）====第十章 UNIX系统内核结构'
    elif x in ['死锁的检测和解除']:
        return '死锁的检测和解除====第三章 处理机调度与死锁'
    elif x in ['流的概念']:
        return '无结构文件/流式文件'
    elif x in ['病毒的隐藏、预防及检测']:
        return '病毒的隐藏、预防及检测====第九章 系统安全'
    elif x in ['设备处理']:
        return '设备处理(包含178,146,140)'
    elif x in ['请求分段存储管理方式']:
        return '请求分段存储管理方式====第四章 存储器管理'
    elif x in ['操作系统的发展历史']:
        return '操作系统'
    elif x in ['第01讲']:
        return '操作系统的基本特性'
    elif x in ['第02讲']:
        return '操作系统的发展历史'
    elif x in ['第03讲']:
        return '操作系统的主要功能'
    elif x in ['第04讲']:
        return '操作系统的结构设计'
    elif x in ['第05讲']:
        return '进程'
    elif x in ['第06讲']:
        return '进程操作'
    elif x in ['第07讲']:
        return '进程调度'
    elif x in ['第08讲']:
        return '进程同步'
    elif x in ['第09讲']:
        return '信号量'
    elif x in ['第10讲']:
        return '管程'
    elif x in ['第11讲']:
        return '临界资源'
    elif x in ['第12讲']:
        return '互斥'
    elif x in ['第13讲']:
        return '进程通信'
    elif x in ['第14讲']:
        return '消息传递'
    elif x in ['第15讲']:
        return '管道通信'
    elif x in ['第16讲']:
        return '共享存储'
    elif x in ['第17讲']:
        return '生产者-消费者问题'
    elif x in ['第18讲']:
        return '哲学家进餐问题'
    elif x in ['第19讲']:
        return '读者-写者问题'
    elif x in ['第20讲']:
        return '线程'
    elif x in ['第21讲']:
        return '互斥锁'
    elif x in ['第22讲']:
        return '读写锁'
    elif x in ['第23讲']:
        return '高级调度/作业调度/长程调度'
    elif x in ['第24讲']:
        return '低级调度/进程调度/短程调度'
    elif x in ['第25讲']:
        return '中级调度/中程调度'
    elif x in ['第26讲']:
        return '先来先服务/FCFS'
    elif x in ['第27讲']:
        return '短作业(进程)优先/SJ(P)F'
    elif x in ['第28讲']:
        return '高优先权优先/FPF'
    elif x in ['第29讲']:
        return '非抢占式优先权算法'
    elif x in ['第30讲']:
        return '抢占式优先权算法'
    elif x in ['第31讲']:
        return '优先权'
    elif x in ['第32讲']:
        return '基于时间片的轮转调度算法'
    elif x in ['第33讲']:
        return '多级反馈队列调度算法'
    elif x in ['第34讲']:
        return '实时调度'
    elif x in ['第35讲']:
        return '最早截止时间优先算法/EDF'
    elif x in ['第36讲']:
        return '最低松弛度优先算法/LLF'
    elif x in ['第37讲']:
        return '多处理器系统'
    elif x in ['第38讲']:
        return '死锁'
    elif x in ['第39讲']:
        return '死锁产生的原因'
    elif x in ['第40讲']:
        return '银行家算法'
    elif x in ['第41讲']:
        return '内存管理'
    elif x in ['第42讲']:
        return '主存储器/内存/主存'
    elif x in ['第43讲']:
        return '寄存器'
    elif x in ['第44讲']:
        return '高速缓冲存储器/Cache'
    elif x in ['第45讲']:
        return '程序'
    elif x in ['第46讲']:
        return '编译'
    elif x in ['第47讲']:
        return '链接'
    elif x in ['第48讲']:
        return '连续分配'
    elif x in ['第49讲']:
        return '单一连续分配'
    elif x in ['第50讲']:
        return '固定分区分配'
    elif x in ['第51讲']:
        return '动态分区分配'
    elif x in ['第52讲']:
        return '空闲分区'
    elif x in ['第53讲']:
        return '哈希算法'
    elif x in ['第54讲']:
        return '交换'
    elif x in ['第55讲']:
        return '非连续内存分配'
    elif x in ['第56讲']:
        return 'f分页'
    elif x in ['第57讲']:
        return '页面'
    elif x in ['第58讲']:
        return '页表'
    elif x in ['第59讲']:
        return 'IO系统'
    elif x in ['第60讲']:
        return '虚拟存储器'
    elif x in ['第61讲']:
        return '中断'
    elif x in ['第62讲']:
        return '直接存储器访问IO控制方式/DMA'
    elif x in ['第63讲']:
        return 'IO通道控制方式'
    elif x in ['第64讲']:
        return '缓冲管理'
    elif x in ['第65讲']:
        return '缓冲寄存器'
    elif x in ['第66讲']:
        return '设备分配'
    elif x in ['第67讲']:
        return '输入井和输出井'
    elif x in ['第68讲']:
        return '磁盘'
    elif x in ['第69讲']:
        return '磁盘调度'
    elif x in ['第70讲']:
        return '文件'
    elif x in ['第71讲']:
        return '文件控制块'
    elif x in ['第72讲']:
        return '文件目录'
    elif x in ['第73讲']:
        return '文件管理方法'
    elif x in ['第74讲']:
        return '文件共享'
    elif x in ['第75讲']:
        return '文件保护'
    elif x in ['死锁产生的原因']:
        return '死锁的产生原因'
    elif x in ['f分页']:
        return '分页'
    else:
        return x

In [27]:
os['title'] = os['title'].apply(lambda x: change_os(x))
os['new_title'] = os['title'].apply(lambda x: True if os_dict.get(x) else False)
os[os['new_title']==False]

Empty DataFrame
Columns: [stuno, title, new_oper, time, new_title]
Index: []

In [28]:
os['new_title2'] = os['title'].apply(lambda x: os_dict.get(x))
os

,stuno,title,new_oper,time,new_title,new_title2
0,1069800109030205,操作系统的目标和作用,tag,1429497734,True,397
1,1069800109030205,连续分配方式,done,1429497741,True,428
2,1069800109030205,对换,done,1429497796,True,429
3,1069800109030205,三级调度的概念及算法准则,done,1429497920,True,417
4,1069800109030205,连续分配方式,tag,1429499516,True,428
...,...,...,...,...,...,...
5601,1069834615030039,系统安全的基本概念,duration,1428396833,True,476
5602,1069850614030008,操作系统的目标和作用,tag,1428674222,True,397
5603,1069850614030008,单道和多道批处理系统,done,1428674265,True,398
5604,1069850614030008,单道和多道批处理系统,duration,1428677285,True,398
5605,1069850614030008,单道和多道批处理系统,tag,1428677286,True,398

In [29]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

os.sort_values(by=['stuno','time'])
os[['new_stuno']] = os[['stuno']].apply(encoder.fit_transform)
new_os = os[['new_stuno','new_title2','new_oper','time']]
new_os['new_stuno'] = new_os['new_stuno'] + 1

/opt/conda/envs/KT_RL/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [30]:
new_os

      new_stuno  new_title2  new_oper        time
0             1         397       tag  1429497734
1             1         428      done  1429497741
2             1         429      done  1429497796
3             1         417      done  1429497920
4             1         428       tag  1429499516
...         ...         ...       ...         ...
5601        304         476  duration  1428396833
5602        305         397       tag  1428674222
5603        305         398      done  1428674265
5604        305         398  duration  1428677285
5605        305         398       tag  1428677286

[4700 rows x 4 columns]

In [31]:
new_os.to_csv('./processed/os_mb_KG.txt',header=None, sep='\t', index=False)
max(new_os['new_title2'])

496

In [32]:
import pandas as pd
net = pd.read_csv('./processed/net_nodul.csv', header=0, sep='\t')
net_count = net.groupby('stuno').count()
net = net[net['stuno'].isin(net_count[net_count['oper']>3].index)][['stuno','title','new_oper','time']]
net

                 stuno       title new_oper        time
0     1069800111030041        离线作业    enter  1413883798
1     1069800111030041        离线作业     done  1413883869
2     1069800111030041        课程公告    watch  1415244162
3     1069800111030041  计算机网络原理(新)      tag  1415330742
11    1069800113030103        课程公告    watch  1414155169
...                ...         ...      ...         ...
4532  1069850614030008        第01讲     done  1429539992
4533  1069850614030008        第02讲     done  1429624580
4534  1069850614030008        第03讲      tag  1429753275
4535  1069850614030008  计算机网络原理(新)      tag  1429794648
4536  1069850614030008        第03讲     done  1429794803

[3596 rows x 4 columns]

In [33]:
net_dict = pd.read_csv('./net/entity2id.txt',sep='\t', names=['entity','id'])
net_dict

                entity   id
0                计算机网络    1
1          计算机网络的产生和发展    2
2               联机网络系统    3
3               分组交换网络    4
4            网络体系结构标准化    5
..                 ...  ...
333               第50讲  334
334               第51讲  335
335  第52讲==== 第十章 网络安全  336
336          第53讲/总复习1  337
337          第54讲/总复习2  338

[338 rows x 2 columns]

In [34]:
net_dict = net_dict.set_index('entity')['id'].to_dict()
net['new_title'] = net['title'].apply(lambda x: True if net_dict.get(x) else False)

In [35]:
net[net['new_title']==False]

                 stuno       title new_oper        time  new_title
0     1069800111030041        离线作业    enter  1413883798      False
1     1069800111030041        离线作业     done  1413883869      False
2     1069800111030041        课程公告    watch  1415244162      False
3     1069800111030041  计算机网络原理(新)      tag  1415330742      False
11    1069800113030103        课程公告    watch  1414155169      False
...                ...         ...      ...         ...        ...
4529  1069834614030133        离线作业     done  1429980210      False
4530  1069834614030133        离线作业    enter  1429980214      False
4534  1069850614030008        第03讲      tag  1429753275      False
4535  1069850614030008  计算机网络原理(新)      tag  1429794648      False
4536  1069850614030008        第03讲     done  1429794803      False

[1959 rows x 5 columns]

In [36]:
set(net[net['new_title']==False]['title'].unique())

{'01',
 '02',
 '03',
 '04',
 '06',
 '07',
 '08',
 '10',
 '11',
 '12',
 '?2',
 '?6',
 'Applet程序执行',
 'Applet程序结构',
 'Cache工作原理',
 'Java平台',
 'Java语言背景',
 '串操作',
 '典型例题',
 '化工热力学内容组织',
 '微型计算机的发展趋势',
 '微机的发展',
 '汇编语言',
 '离线作业',
 '第03讲',
 '第06讲',
 '第09讲',
 '第13讲',
 '第14讲',
 '第19讲',
 '第22讲',
 '第24讲',
 '第25讲',
 '第30讲',
 '第31讲',
 '第34讲',
 '第36讲',
 '第37讲',
 '第39讲',
 '第40讲',
 '第41讲',
 '第42讲',
 '第43讲',
 '第48讲',
 '第52讲',
 '第53讲',
 '第54讲',
 '菜单组件',
 '计算机网络原理(教育网)',
 '计算机网络原理(新)',
 '计算机网络原理(电信网)',
 '计算机网络原理(简版)',
 '论坛',
 '课程介绍',
 '课程公告'}

In [39]:
def change_net(x):
    if x in ['?2', '?6', 'Applet程序执行', 'Applet程序结构', 'Cache工作原理', 'Java平台', 'Java语言背景', '串操作', '典型例题', '化工热力学内容组织', '微型计算机的发展趋势', '微机的发展', '汇编语言', '离线作业','计算机网络原理(教育网)', '计算机网络原理(新)', '计算机网络原理(电信网)', '计算机网络原理(简版)', '论坛', '课程介绍', '课程公告', '菜单组件']:
        return '计算机网络'
    elif x in ['01']:
        return '第01讲'
    elif x in ['02']:
        return '第02讲'
    elif x in ['第03讲','03']:
        return '第03讲==== 第一章 引论'
    elif x in ['04']:
        return '第04讲'
    elif x in ['06','第06讲']:
        return '第06讲（包含62）'
    elif x in  ['07']:
        return '第07讲'
    elif x in ['08']:
        return '第08讲'
    elif x in ['第09讲']:
        return '第09讲==== 第二章 数据通信基础知识'
    elif x in ['10']:
        return '第10讲'
    elif x in ['11']:
        return '第11讲'
    elif x in ['12']:
        return '第12讲'
    elif x in ['第13讲']:
        return '第13讲（包括128,139,140）==== 第三章 计算机网络体系结构'
    elif x in ['第14讲']:
        return '第14讲（包含50,148,150）'
    elif x in ['第19讲']:
        return '第19讲==== 第四章 计算机网络体系结构'
    elif x in ['第22讲']:
        return '第22讲(包含151)'
    elif x in ['第24讲']:
        return '第24讲(包含139,140)==== 第五章 网络互联与英特网基础'
    elif x in ['第25讲']:
        return '第25讲（包含6）'
    elif x in ['第30讲']:
        return '第30讲（包含214）'
    elif x in ['第40讲']:
        return '第40讲（包含178,179）'
    elif x in ['第31讲']:
        return '第31讲（包含219）==== 第六章 局域网'
    elif x in ['第34讲']:
        return '第34讲（包含186,187）'
    elif x in ['第36讲']:
        return '第36讲（包含234）'
    elif x in ['第37讲']:
        return '第37讲（包含236,24,7,169）==== 第七章 广域网'
    elif x in ['第39讲']:
        return '第39讲（包含176,177,240,241）'
    elif x in ['第41讲']:
        return '第41讲（包含179,220）'
    elif x in ['第42讲']:
        return '第42讲（包含136,137,192,193）'
    elif x in ['第43讲']:
        return '第43讲（包含137,178,180）==== 第八章 常用网络设备'
    elif x in ['第48讲']:
        return '第48讲==== 第九章 网络操作系统'
    elif x in ['第52讲']:
        return '第52讲==== 第十章 网络安全'
    elif x in ['第53讲']:
        return '第53讲/总复习1'
    elif x in ['第54讲']:
        return '第54讲/总复习2'
    else:
        return x

In [40]:
net['title'] = net['title'].apply(lambda x: change_net(x))
net['new_title'] = net['title'].apply(lambda x: True if net_dict.get(x) else False)
net[net['new_title']==False]

Empty DataFrame
Columns: [stuno, title, new_oper, time, new_title]
Index: []

In [41]:
net

                 stuno            title new_oper        time  new_title
0     1069800111030041            计算机网络    enter  1413883798       True
1     1069800111030041            计算机网络     done  1413883869       True
2     1069800111030041            计算机网络    watch  1415244162       True
3     1069800111030041            计算机网络      tag  1415330742       True
11    1069800113030103            计算机网络    watch  1414155169       True
...                ...              ...      ...         ...        ...
4532  1069850614030008             第01讲     done  1429539992       True
4533  1069850614030008             第02讲     done  1429624580       True
4534  1069850614030008  第03讲==== 第一章 引论      tag  1429753275       True
4535  1069850614030008            计算机网络      tag  1429794648       True
4536  1069850614030008  第03讲==== 第一章 引论     done  1429794803       True

[3596 rows x 5 columns]

In [42]:
net['new_title2'] = net['title'].apply(lambda x: net_dict.get(x))
net

,stuno,title,new_oper,time,new_title,new_title2
0,1069800111030041,计算机网络,enter,1413883798,True,1
1,1069800111030041,计算机网络,done,1413883869,True,1
2,1069800111030041,计算机网络,watch,1415244162,True,1
3,1069800111030041,计算机网络,tag,1415330742,True,1
11,1069800113030103,计算机网络,watch,1414155169,True,1
...,...,...,...,...,...,...
4532,1069850614030008,第01讲,done,1429539992,True,285
4533,1069850614030008,第02讲,done,1429624580,True,286
4534,1069850614030008,第03讲==== 第一章 引论,tag,1429753275,True,287
4535,1069850614030008,计算机网络,tag,1429794648,True,1
4536,1069850614030008,第03讲==== 第一章 引论,done,1429794803,True,287

In [43]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

net.sort_values(by=['stuno','time'])
net[['new_stuno']] = net[['stuno']].apply(encoder.fit_transform)
new_net = net[['new_stuno','new_title2','new_oper','time']]
new_net['new_stuno'] = new_net['new_stuno'] + 1

/opt/conda/envs/KT_RL/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [44]:
new_net

      new_stuno  new_title2 new_oper        time
0             1           1    enter  1413883798
1             1           1     done  1413883869
2             1           1    watch  1415244162
3             1           1      tag  1415330742
11            2           1    watch  1414155169
...         ...         ...      ...         ...
4532        246         285     done  1429539992
4533        246         286     done  1429624580
4534        246         287      tag  1429753275
4535        246           1      tag  1429794648
4536        246         287     done  1429794803

[3596 rows x 4 columns]

In [45]:
new_net.to_csv('./processed/net_mb_KG.txt',header=None, sep='\t', index=False)

In [46]:
max(new_net['new_title2'])

338